### PR TITLE
fix(schematic): don't add the plugin if already added

### LINKED ISSUE #192: ng-add schematic adds this plugin multiple times
## Behavior

I've run the `ng add` schematic on the NgRx repo, and the result was that the NgRx ESLint plugin was added multiple times to the same config.

## Code snippet

```json
{
      "plugins": [
        "ngrx",
        "ngrx",
        "ngrx"
      ],
      "extends": [
        "plugin:ngrx/recommended",
        "plugin:ngrx/recommended",
        "plugin:ngrx/recommended"
      ]
}
```

and

```json
{
      "plugins": [
        "eslint-plugin-import",
        "@typescript-eslint",
        "ngrx",
        "ngrx",
        "ngrx"
      ],
      "extends": [
        "plugin:ngrx/recommended",
        "plugin:ngrx/recommended",
        "plugin:ngrx/recommended"
      ]
}
```

## I would be willing to submit a PR to fix this issue :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by timdeschryver**
Closes #192

### CODE REVIEW

File: src/schematics/ng-add/index.ts [hunk 1]
```diff
@@ -55,6 +55,14 @@ function configurePlugin(json: {
...
+  json.plugins = json.plugins || []
+  json.extends = json.extends || []
+
+  if (!json.plugins.includes('ngrx')) {
+    json.plugins.push('ngrx')
+  }
+
+  if (!json.extends.includes('plugin:ngrx/recommended')) {
+    json.extends.push('plugin:ngrx/recommended')
+  }
```
Comment (rafaelss95) [inline src/schematics/ng-add/index.ts:67]: Maybe?

```suggestion
  json.plugins = [...new Set([...json.plugins ?? []), 'ngrx')]
  json.extends = [...new Set([json.extends ?? []), 'plugin:ngrx/recommended')]
```

Comment (timdeschryver) [reply src/schematics/ng-add/index.ts]: Yep, that also works 👍
