### PR TITLE
fix(avoid-combining-selectors): detect violation with select pipe

### LINKED ISSUE #75: [avoid-combining-selectors] Unexpected behaviors
Similar to #74,

1. It doesn't report when we use something other than `store`:

`readonly something$ = combineLatest(this.store$.select(AuthSelectors.selectUser), this.store$.select(AuthSelectors.something))`

2. It doesn't report when we use `store.pipe` instead of `store.select`:

`readonly something$ = combineLatest(this.store$.pipe(select(AuthSelectors.selectUser)), this.store$.select(AuthSelectors.something))`

### PR DESCRIPTION
**Pull request by timdeschryver**
Closes #75

### CODE REVIEW

File: src/rules/store/avoid-combining-selectors.ts [hunk 1]
```diff
@@ -40,14 +40,7 @@ export default ESLintUtils.RuleCreator(docsUrl)<Options, MessageIds>({
         node: TSESTree.CallExpression,
```
Comment (rafaelss95) [inline src/rules/store/avoid-combining-selectors.ts:40]: I think you could achieve the same result using the existent selectors, no?

```suggestion
    const pipeableOrStoreSelect = `:matches(${storeExpression(
      storeName,
    )}[callee.property.name='pipe']:has(CallExpression[callee.name='select']), ${storeSelect(
      storeName,
    )})`

    return {
      [`CallExpression[callee.name='combineLatest'][arguments.length>1] ${pipeableOrStoreSelect} ~ ${pipeableOrStoreSelect}`](
        node: TSESTree.CallExpression,
      ) {
        context.report({
          node,
          messageId,
        })
      },
```

Comment (timdeschryver) [reply src/rules/store/avoid-combining-selectors.ts:40]: Nice! 🤩
