### PR TITLE
fix(avoid-mapping-selectors): report within `pipe` and `select`

### LINKED ISSUE #174: False positive with combineLatest (ngrx/avoid-mapping-selectors)
## Behavior

When combining store with another observable and map the linter tells me to use selectors

## Code snippet

```ts
combineLatest([this.store.select(selectAuthorizations), this.hasAuthorization$]).pipe(map((val) => !isEmpty(intersection(val))))
```

## I would be willing to submit a PR to fix this issue :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

### PR DESCRIPTION
**Pull request by rafaelss95**
Fixes #174.

### CODE REVIEW

File: src/rules/store/avoid-mapping-selectors.ts [hunk 1]
```diff
@@ -29,16 +34,15 @@ export default ESLintUtils.RuleCreator(docsUrl)<Options, MessageIds>({
...
+    )}:has(CallExpression[callee.name='select'] ~ CallExpression[callee.name='map'])`
+    const selectSelector = `${storeExpressionCallable(
       storeName,
-    )}:has(CallExpression[callee.name="select"])`
-    const pipeExpressions = [mapInSelect, mapInPipe].join(', ')
+    )}[callee.object.callee.property.name='select']`
 
     return {
-      [`:matches(${pipeExpressions}) > CallExpression[callee.name='map']`](
+      [`:matches(${selectSelector}, ${pipeWithSelectAndMapSelector}) CallExpression[callee.name='map']`](
```
Comment (rafaelss95) [inline src/rules/store/avoid-mapping-selectors.ts:45]: I think it worths to mention that the following case is not covered by this selector:

subsequent pipes

But I don't think people really use it like this in real world 🤷🏼‍♂️.

Comment (timdeschryver) [reply src/rules/store/avoid-mapping-selectors.ts:45]: Yea... we're not going to support that 😅

Comment (rafaelss95) [reply src/rules/store/avoid-mapping-selectors.ts:45]:
```suggestion
      [`:matches(${selectSelector}, ${pipeWithSelectAndMapSelector}) > CallExpression[callee.name='map']`](
```

**Review by timdeschryver — APPROVED** [review]
